### ISSUE TITLE
Before Alpha Release

### ISSUE THREAD

**Issue by hzoo** [babel/babili#31]
- [x] move minification plugins out of babe/babel #33
- [x] wrap babel-cli #49
- [x] guide/how to use it #50
  - [x] as a babel preset/plugin
  - [x] using the cli standalone

> can't we just make the `babel-minify` executable a `child.process` that calls out to the `babel` CLI just with a `--presets minify` argument appended?

- [x] reasoning, and how it works (explanation about how babel is a compiler and optimization is just another thing that it can do just like converting es2015, it should be faster since it's the same tool and can be run as part of your babel build)

---
- [x] make sure the names aren't taken: #8 #46
- [x] remove minify plugins from babel/babel https://github.com/babel/babel/pull/3621 and transfer any updates #75 
- [x] publish all packages as alpha, ask for testers/help
- [x] transfer repo to babel org, make public
- [x] Online demo/try it out: https://github.com/amasad/babel-minify/issues/28 (would be nice to turn on/off plugins individually, time to minify)

---
After
- [x] transfer relevant PRs to move to minify
- [x] add greenkeeper https://github.com/amasad/babel-minify/issues/74

**Comment by hzoo** [comment]
I think we did most of these
